accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'accounts'

urlpatterns = [
    path('index/', views.indexView, name="index"),
    path('login/', LoginView.as_view(), name = 'login_url'),
    path('register/',views.registerView, name='register_url'),
    path('logout/',LogoutView.as_view(next_page="homeprof:profile"), name="logout_url")

]

homeprof/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'homeprof'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('books/', views.books, name='books'),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')), 
    path('', include('homeprof.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

homeprof/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

def indexView(request):
    return render(request, 'index.html')


def registerView(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login_url')
    else:
        form = UserCreationForm() 
    return render(request, 'register.html', {'form': form})

homeprof/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required


def profile(request):
    return render(request, 'profile.html')

@login_required
def books(request):
    return render(request, 'books.html')

accounts/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Radley&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/1927c4eb85.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="{% static 'css/logg.css' %}">
    <title>Login</title>
</head>
<body>
       
        <h1 class="oops"> Oops! You have to log in first</h1>
        <br>
        {% if user.is_authenticated %}
            <a href="{% url 'accounts:logout_url' %}">Logout</a>
            {% else %}
            <div class="logreg">
                <a class="choose" href="{% url 'accounts:login_url' %}">LogIn</a>
                <a class="choose" href="{% url 'accounts:register_url' %}">Register</a>
            </div> 
        {% endif %}
   
</body>
</html>

accounts/templates/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Radley&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/1927c4eb85.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="{% static 'css/logg.css' %}">
    <title>Login</title>
</head>
<body>
        <h1 class=oops id='create'>Create New Account</h1>
    <form method="POST">
         {% csrf_token %}
        <div class="login" id="reg">
        <br>
        <br>
        {{form.as_p}}
        <button class='logbut'>Register</button>
        </div>
    </form>
</body>
</html>

homeprof/templates/books.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Radley&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/1927c4eb85.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <title>odilas profile</title>
</head>
<body>

        <nav class="navbar navbar-expand-lg navbar-light nav-home">
                <a class="navbar-brand"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                    
                <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
                    <div class="navbutton navbar-nav">
                        {% if user.is_authenticated %}
                        <p id= username> Hi, {{ user.username }}  </p>
                        <br>
                        <a class="nav-item nav-link" style = "color: white;" href="{% url 'accounts:logout_url' %}">logout</a>
                        {% else %}
                        <a class="nav-item nav-link active" style="color : rgb(248, 226, 165);" ref="{% url 'homeprof:books' %}">books</a>
                        {% endif %}
                        <a class="nav-item nav-link" style="color : white;" href="{% url 'homeprof:profile' %}">profile</a>
                    </div>
                </div>
            </nav>

            {% if user.is_authenticated %}
     
   
    <div class="semuamua">
        <br>
        <br>
            <div class="search">
                <br>
                <h1 id="searchTitle">Book Catalogue</h1>
                <div class="searchBox">
                    <input class="search-txt" type="search" id="searchField" name="" value="" placeholder=" Type to search">
                    <button class="search-btn" type="button" name="button"><i class="fas fa-search"></i></button>
                </div>
                <br>
                <br>
                <br>
                <br>
                <br>
                <table class="table"></table>
            </div>
    </div>
    
    {% else %}
    <a href="{% url 'accounts:login_url' %}">Login</a>
    <a href="{% url 'accounts:register_url' %}">Register</a>
    {% endif %}

          
<script src="https://code.jquery.com/jquery-1.11.3.js"></script>
<script src="{% static 'js/books.js' static %}"></script>
            
</body>
</html>

homeprof/templates/profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Radley&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/1927c4eb85.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>odilas profile</title>
</head>
<body class="light">
        <nav class="navbar navbar-expand-lg navbar-light nav-home">
                <a class="navbar-brand"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                    
                <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
                    <div class="navbutton navbar-nav">
                        {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'homeprof:books' %}">books</a>
                        {% else %}
                        <a class="nav-item nav-link" href="{% url 'accounts:index' %}">login</a>
                        {% endif %}
                        <a class="nav-item nav-link active" style="color :  rgb(187, 142, 17);" href="{% url 'homeprof:profile' %}">profile</a>
                    </div>
                </div>
            </nav>

    <p id="greeting">hey! it's odi</p>
    <button class="btn nightbutton"><i class="far fa-moon"></i></button>

    <br>
    <br>
    <br>
                    <div class="box">
                            <div class="about">
                                    <button class="accordion">activities</button>
                                    <div class="panel one">
                                        <p>bingewatching kalo ga ada tugas & kuis</p>
                                    </div>
                                    <br>
                                    <button class="accordion">experiences</button>
                                    <div class="panel two">
                                        <p>Staff Departemen Seni Budaya BEM Fasilkom UI 2019</p>
                                        <p>Staff Fundraising Compfest 11</p>
                                        <p>Staff Dekor CGT </p>
                                    </div>
                                    <br>
                                    <button class="accordion">achievements</button>
                                    <div class="panel three">
                                        <p>belom ada :(</p>
                                    </div>
                                </div>    
                    </div>

            
 
                       

            


    


   




    <script src="{% static 'js/accordion.js' %}"></script>
    <script src="{% static 'js/theme.js' %}"></script>
</body>
</html>